### ISSUE TITLE
bigMHC retraining

### ISSUE THREAD

**Issue by Atefeh547** [KarchinLab/bigmhc#12]
Hi dear, 
I have a question about retraining or transfer learning bigmhc on new immunogenicity dataset, 
I am a beginner in programming, i splitted new dataset in training and testing. 
This is my command for retraining the model:
$ python train.py -i=training.csv -a=HLA-A*02:01 -t=2  -o=pathToDirectory 
I dont want to optimize batch and epoch number and using the same in model :(batch,epoch) (16,23), (16,23), (8,15), (64,62), (32,27), (32,31) and (64,54)
My question is : i must retrain model each time with one of the seven batch and epoch numbers and save parameters then replacing the parameters with the original parameters of the model into models folder?  
and then testing performance of model by this command:
$ python predict.py -i=testing.csv -m=im -a=HLA-A*02:01 -t=2 
please guide me in this problem.

**Comment by benjaminalbert** [comment]
Retraining in this manner indicates that:
* you have only HLA-A*02:01 data in the `training.csv` file
* the third column of the csv contains the target scores
* the output directory is being set to `pathToDirectory`
* `training.csv` has a single row of header information, since the `-c` argument is unused and the default is `1`

To transfer learn, the other arguments you should specify are:
* the base model with the `-m` argument, such as `-m=models/bat512` to transfer learn starting from the bat512 EL model or `-m=models/bat512/im` to transfer learn starting from the bat512 IM model.
* the batch size for retraining, such as `-b=16`
* the number of epochs, such as `-e=50`

After you train for some number of epochs, the output will be saved in multiple `ep` subdirs within your specified `out` dir. You should then identify the epoch at which the model performed best on validation data (i.e. by using the `predict.py` script) as described in the publication. Because you are transfer learning, only the transfer-learned layers will be saved in each `ep` dir.

Once you identify the `ep` dir that performs best, you can move it to within the base model dir. For example, suppose you transfer learned from base model `bat512` and epoch 20 performs best; then, you would move the `ep20` dir to the `bat512` dir. After this, you can use your transfer-learned model by specifying the model arg as `-m=bat512/ep20`. You can rename the ep20 to whatever you want upon moving it to the base model dir (e.g. `-m=bat512/my_new_im_predictor`).

When you specify the path to an IM model such as `bat512/my_new_im_predictor` (or our own trained `bat512/im`), it uses the transfer-learned layers in that IM directory (e.g. `bat512/my_new_im_predictor`) and initializes the remaining layer weights from the parent directory (e.g. `bat512`).

**Comment by Atefeh547** [comment]
Thank you so much for your detailed explanation benjamin.
